# EVERFOREST
[colors.bright]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.normal]
black = "#4b565c" 
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.primary]
background = "#2D353B"
foreground = "#d3c6aa"

[font]
# size = 12.5
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font"
# family= "JetBrainsMono NFM"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_title = true
startup_mode = "Windowed"
opacity = 1.0

[window.dimensions]
columns = 120
lines = 36

[cursor]
blink_interval = 250

[cursor.style]
shape = "Block"
blinking = "Always"

[window.padding]
x = 30
y = 30
